### ISSUE TITLE
0.6.2 crashes build 1007

### ISSUE THREAD

**Issue by MajusCorp** [jenskutilek/RedArrow-Glyphs#15]
OS X 10.10.5, Build 1007 -- In font window, Select Glyphs With Outline Errors panel open, click OK using defaults, G2 crashes consistently. Crash report sent to Georg.

**Comment by jenskutilek** [comment]
Could you try updating to the current version 0.6.3? I think it’s resolved. Not Georg’s fault :)

**Comment by MajusCorp** [comment]
Not fixed. Double-checked the .plist, it is indeed 0.6.3 installed after updating it a few minutes ago.

**Comment by jenskutilek** [comment]
Could you send me a crash report?

**Comment by MajusCorp** [comment]
Attached two reports: System and Glyphs. Glyphs report begins at line 665.

**Comment by MajusCorp** [comment]
Hmm. I don't see an attachment to my previous reply, so I'm adding it here.

[Crash Reports.txt](https://github.com/jenskutilek/RedArrow-Glyphs/files/914861/Crash.Reports.txt)

**Comment by jenskutilek** [comment]
Could you try updating to 0.6.4? That should hopefully fix it.

(It was caused by an older RoboFab installation, which is used for the dialog window. I have now included the window modules directly in RedArrow so it doesn't rely on a RoboFab installation.)

**Comment by MajusCorp** [comment]
Not fixed; in fact, Red Arrow does not appear anywhere in Glyphs except in the Plug-In Manager as installed. Nothing under Edit, Reporter Panel, et al.

This morning I tried some more troubleshooting here: 
1. Reinstalled RoboFab and other modules
2. Ran system utility to verify Directory structures
3. Moved working Glyphs file to Desktop of startup drive
4. Reinstalled Red Arrow manually. One difference from previous manual installs of plug-ins is that I got a message that it appears to be a Github repository, do I want to alias it or copy it. I did a copy. That didn't change anything so I removed it and reinstalled it through Plug-In Manager.

One other oddity about Red Arrow is that when 0.6.2 was first issued I noticed it had a date of January 2016; 0.6.3 had a date of May 2016. Is that significant? Also in the Plug-In Manager, the entry for Red Arrow has a description but the image that normally shows is blank.

Question: is anyone else reporting a problem with Red Arrow? I'm suspecting it is something at my end of the chain.

**Comment by MajusCorp** [comment]
Additional info:
I just finished testing RA on my Sierra startup drive which still has RA 0.5.3 installed on it. It crashes too.

This is all showing up now because I had never selected the entry under Edit so wasn't aware of the crashing until this latest update. 

One change to the crashing is that now the RA panel never appears before the crash. Prior, it was crashing when I selected OK. It exhibited that behavior with 0.5.3 also.

Even more, this to me indicates something with my system. I will try some other things later today.

**Comment by MajusCorp** [comment]
I just remembered I can't do any further testing because RA doesn't appear anywhere in Glyphs with 0.6.4. Can I get another copy of 0.6.2 or 0.6.3 to test with?

**Comment by jenskutilek** [comment]
If no menu entry and no arrows appear in Glyphs, there is probably a problem that prevents the loading of the plugin. Then there should be a message about RedArrow in the Console.app log during Glyphs startup. When you filter the messages for "glyphs", something should come up. It would be good to know what it says.

The modification dates of the plugin don't mean much, they apply only to the plugin package, not the actual script files contained in them.

If you want to install oder versions manually, you can get them from [here](https://github.com/jenskutilek/RedArrow-Glyphs/tags).

**Comment by MajusCorp** [comment]
0.6.4 currently installed; this is Console report:

4/12/17 15:52:01.962 Glyphs[10815]: RedArrow has encountered a fatal error, and will now terminate.
4/12/17 15:52:01.963 Glyphs[10815]: An uncaught exception was raised during execution of the main script:

NameError: name '_baseWindowController' is not defined

This may mean that an unexpected error has occurred, or that you do not have all of the dependencies for this bundle.
4/12/17 15:52:01.963 Glyphs[10815]: Problem with Plugin at Path: /Users/georgethomas2/Library/Application Support/Glyphs/Repositories/RedArrow/RedArrow.glyphsReporter
4/12/17 15:52:01.963 Glyphs[10815]: Problem with Plugin at Path: /Users/georgethomas2/Library/Application Support/Glyphs/Repositories/RedArrow/RedArrow.glyphsReporter (protocol)

**Comment by jenskutilek** [comment]
That looks like "vanilla" is not installed. RedArrow shouldn't crash though.

In v0.6.6 I have included vanilla in the plugin download, could you try it?

**Comment by MajusCorp** [comment]
Not fixed, but... here's what I did that fixed it, just now:
Through Plug-In Manager, removed Red Arrow, then downloaded the package labeled 0.6.1 (which actually contains 0.6.0), installed it manually, and once more Red Arrow works -- perfectly.
Then to test it again, I manually installed the update to 0.6.2 -- and it still works.
So, to test it again, I did the automatic update install to 0.6.6 -- and it killed Red Arrow again.
For now I will go back and repeat my previous fix to get it working through 0.6.2.

**Comment by MajusCorp** [comment]
Here's the latest Console information. Currently have v0.6.3 installed and it works perfectly. See my comment at the top of the Console report.
[Console Log 04-12-17.txt](https://github.com/jenskutilek/RedArrow-Glyphs/files/918202/Console.Log.04-12-17.txt)

**Comment by jenskutilek** [comment]
It seems that vanilla is still the culprit. There are some messages regarding an error loading a vanilla submodule. I suggest you remove the vanilla module from your Python installation and install it again fresh (e.g. through Glyphs: Preferences > Addons > Modules).

**Comment by MajusCorp** [comment]
Removed and reinstalled; results are the same. v0.6.3 is the latest version that works correctly. Later versions, RA does not appear in the app UI.

**Comment by MajusCorp** [comment]
0.6.7 fixed it. Thank you.
