### ISSUE TITLE
Errors Not Showing Up

### ISSUE THREAD

**Issue by weiweihuanghuang** [jenskutilek/RedArrow-Glyphs#20]
Version 2.5.1 (1134)
I recall fractional scaling, and floating point co-ordinates used to show up, now they don't?

**Comment by jenskutilek** [comment]
Indeed, there are some crash messages in the console. I’ll have to check whether Georg or me messed up ;)

**Comment by weiweihuanghuang** [comment]
Think it started since 2.5 😄
