### ISSUE TITLE
Vanilla not detected?

### ISSUE THREAD

**Issue by weiweihuanghuang** [jenskutilek/RedArrow-Glyphs#22]
I get this error:
>Please install vanilla to enable UI dialogs for RedArrow. You can install vanilla through Glyphs > Preferences > Addons > Modules.

But definitely have Vanilla: 
`<module 'vanilla' from '/Library/Python/2.7/site-packages/vanilla-0.1-py2.7.egg/vanilla/__init__.pyc'>`

Version 2.5.1 (1138)

**Comment by jenskutilek** [comment]
What's the output when you run this from the macro panel?

```python
import imp
imp.find_module('vanilla')
```

**Comment by weiweihuanghuang** [comment]
```
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ImportError: No module named vanilla
```
Strange! What's this mean...?

**Comment by jenskutilek** [comment]
@schriftgestalt suggested using `imp` to test availability of `vanilla`. But apparently it can not find modules that are installed as egg files, while the Python importer finds them ... how did you install vanilla?

**Comment by weiweihuanghuang** [comment]
i installed it with the settings inside i.e. `python setup.py install`, strange because other scripts that need vanilla work fine...?

**Comment by jenskutilek** [comment]
It's only the vanilla detection that fails, otherwise it would work. I tried changing the detection in 9d0ab4c99a6c0519bb776a2041657183effd1b1e, could you try?

**Comment by weiweihuanghuang** [comment]
Good now 👍
