### ISSUE TITLE
Red Arrow is broken again in Glyphs latest beta Version 2.5.2 (1147)

### ISSUE THREAD

**Issue by jimwasco** [jenskutilek/RedArrow-Glyphs#24]
Red Arrow is broken again in Version 2.5.2 (1147). I tried reinstalling Red Arrows via the plugins manager and get “Task exited with status 128” error message. I installed Red Arrows by double clicking on the GlyphsReporter plugin file and reinstalling the modules vanilla. After restarting Glyphs the plugin manager shows Red Arrows as not installed and I get the following output in the macro panel

Traceback (most recent call last):
File “GlyphsApp/GlyphsApp/plugins.py”, line 1152, in drawForegroundForLayer_options_
File “/Users/wascoj/Library/Application Support/Glyphs/Plugins/RedArrow.glyphsReporter/Contents/Resources/plugin.py”, line 104, in foreground
self._updateOutlineCheck(layer)
File “/Users/wascoj/Library/Application Support/Glyphs/Plugins/RedArrow.glyphsReporter/Contents/Resources/plugin.py”, line 216, in _updateOutlineCheck
layer.drawPoints(outline_test_pen)
File “GlyphsApp/GlyphsApp/init.py”, line 5954, in DrawPointsWithPen
File “GlyphsApp/GlyphsApp/init.py”, line 6794, in GSPath__drawPoints
File “/Users/wascoj/Library/Application Support/Glyphs/Plugins/RedArrow.glyphsReporter/Contents/Resources/miniFontTools/pens/pointPen.py”, line 112, in endPath
self._flushContour(segments)
File “/Users/wascoj/Library/Application Support/Glyphs/Plugins/RedArrow.glyphsReporter/Contents/Resources/outlineTestPenGlyphs.py”, line 88, in _flushContour
super(OutlineTestPenGlyphs, self)._flushContour(reordered_segments)
File “/Users/wascoj/Library/Application Support/Glyphs/Plugins/RedArrow.glyphsReporter/Contents/Resources/outlineTestPen.py”, line 613, in _flushContour
self._prev_ref = prev_points[-2][0]
IndexError: list index out of range

**Comment by jenskutilek** [comment]
Thanks for reporting. This is actually a good thing, because for the first time the PointPen object works as it should in Glyphs, and all workarounds I had to provide are not necessary anymore. I fixed the problem in v0.8.5, try to update Red Arrow.
