### ISSUE TITLE
Doesn't  work for new macos (macOS Catalina)

### ISSUE THREAD

**Issue by anuki** [jenskutilek/RedArrow-Glyphs#25]
![image](https://user-images.githubusercontent.com/3535095/67216638-94985a00-f434-11e9-95ed-8a575e477ced.png)

**Comment by jenskutilek** [comment]
Could you try to delete it and install it again through the plugin manager? That should fix the problem.

**Comment by anuki** [comment]
I did it just now and it worked! thanks! :)
