### ISSUE TITLE
Fractional transformations after simple rotation

### ISSUE THREAD

**Issue by davewhitley** [jenskutilek/RedArrow-Glyphs#26]
After rotating a simple component, I get a Fractional transformations error. I just used the rotation tool in the right sidebar to rotate it 180 degrees. Is this expected? What is fractional transformation mean exactly?

<img width="324" alt="Screen Shot 2020-06-03 at 9 03 05 PM" src="https://user-images.githubusercontent.com/618551/83706647-a43c6b80-a5dd-11ea-969f-5037c339a41e.png">

**Comment by jenskutilek** [comment]
There was indeed a bug. The test was supposed to check if the offset of the component has integer coordinates, but it checked all components of the transformation matrix for fractional numbers. Those are necessary for a rotated component, and are completely OK.
