### ISSUE TITLE
Fails to detect semi-horizontal lines on 'last point .. first point' lines

### ISSUE THREAD

**Issue by weiweihuanghuang** [jenskutilek/RedArrow-Glyphs#3]
Only in one direction, this ones okay:
![screen shot 2015-06-16 at 11 28 13 am](https://cloud.githubusercontent.com/assets/1271897/8179961/c7b987be-141a-11e5-9468-cb94586a4e9c.png)
Not this one:
![screen shot 2015-06-16 at 11 28 15 am](https://cloud.githubusercontent.com/assets/1271897/8179962/c7badd9e-141a-11e5-80a6-a3a333ca9b89.png)

**Comment by jenskutilek** [comment]
Are you using the most recent version? I thought I had fixed this already, along with the bogus Collinear vectors warning.

**Comment by weiweihuanghuang** [comment]
My apologies, I didn't realise it was updated! It works :)
