### ISSUE TITLE
When I install the latest version of Red Arrow, Glyphs 2.6.6 fails to start with an error

### ISSUE THREAD

**Issue by fontdasu** [jenskutilek/RedArrow-Glyphs#30]
I'm using Glyphs 2.6.6 (1350).
When I install the latest version of Red Arrow, Glyphs 2.6.6 fails to start with an error.

**Comment by jenskutilek** [comment]
Thanks! This should be fixed by https://github.com/schriftgestalt/GlyphsSDK/commit/1923d437dfea61c42f8eb6bb6845bbfedc8e201b / 6d7aed5900f964cced22edf435fddf26913d13a6.
