### ISSUE TITLE
Labels don't appear unless clicked

### ISSUE THREAD

**Issue by weiweihuanghuang** [jenskutilek/RedArrow-Glyphs#31]
I'm on Glyphs Version 2.6.7 (1355) using the latest version of Red Arrows (1.0.1?). The text labels don't appear unless I click near the red arrow? Is this a new feature?

**Comment by weiweihuanghuang** [comment]
Ah I see the show error labels option!

**Comment by jenskutilek** [comment]
No, it's a legitimate bug ... the labels should appear in any case as soon as the mouse pointer is close to an arrow. But often the redraw is not triggered when the mouse is moved, though the plugin subscribes to the MOUSEMOVED callback. @schriftgestalt do you have any idea how to improve this?

When you "Show error labels", and then "Hide error labels" again, the mouse-sensitive drawing suddenly works, but you have to do it every time you open a document.

**Comment by jenskutilek** [comment]
Thank you @schriftgestalt!
