### ISSUE TITLE
Interference with other Plugin(s)

### ISSUE THREAD

**Issue by Mark2Mark** [jenskutilek/RedArrow-Glyphs#33]
Sometimes I had users reporting, that my Variable Font Preview goes a little loco when the Red Arrows Plugin is also active.

I could now reproduce this while improving management of multiple fonts. Once Red Arrows is active, VFP can only deal with the first open font well. Wenn switching to another font, the redrawing gets very glitchy.

@jenskutilek do you happen to have an idea what part of Red Arrows could potentially cause other plugins to be affected in a way or another?

VFP is written in objc and I am prefixing all my classes. Currently I am rather clueless.

Edit: It is even more curious: When I launch Glyphs with Red Arrows off, VFP also behaves odd in some spots, then I turn RA on, and it keeps odd, but when turning RA off *then*, all is fine. :D

Not blaming your code at all. Just wanted add it for the record …

**Comment by schriftgestalt** [comment]
It might be related to assigning the current window controller for each drawing operation. And with the mouse moved callbacks from Red Arrows that might get called in the wrong order or is overwriting things.

**Comment by Mark2Mark** [comment]
Thanks! Is there anything I can improve on my side? I am currently fixing the currentFontDocument handling. Maybe a way of checking for the correct window controller in my drawing operations?

**Comment by schriftgestalt** [comment]
I would need to check the code that access the the fonts. 
and what is actually not working?

**Comment by Mark2Mark** [comment]
It’s quite hard to describe. I’ll clean up the messy code a bit and then will show you. Basically when it works weidly, the live update on slider changes of the drawing happens only in the first opened font document, but only updates **_after_** a slider changed and the mouse is let go in all other font documents.

Then, when I enable Red Arrows, the same happens. But when I then disable RA, and wiggle around the sliders, the live update works well in all open documents.

**Comment by jenskutilek** [comment]
If I remember correctly, Georg optimized a part of my code so that the outline check doesn't need to be updated that often.

I vaguely remember that I had similar experiences as you, @Mark2Mark, in that the updating and the live showing/hiding of error labels works more reliably when it is once deactivated (context menu: Show Error Labels), then activated again. I never really found out what causes this.

Sorry that I can't be of more help ...

**Comment by Mark2Mark** [comment]
Adding some investigation. As it seemed to "fix" VFP when RA is enabled and disabled again, we thought to start looking into the willDeactivate method. There RA calls `self.stopMouseMoved()` which again only calls `NSNotificationCenter.defaultCenter().removeObserver_(self)`

Interesting is, that `self.stopMouseMoved()` is also called from `toggleLabels_`. So I tried with the oddly behaving VFP, activating RA, but now instead of deactivating it, toggling the Error Label setting, which as expected also "fixes" VFP.

The RA observer of interest here is `NSNotificationCenter.defaultCenter().addObserver_selector_name_object_(self, self.mouseDidMove_, MOUSEMOVED, objc.nil)`. Not sure if that helps anyone of us, but it could be a hint.

**Comment by Mark2Mark** [comment]
Last discovery from Georg’s tip:

```py
def mouseDidMove_(self, notification):
	pass # Glyphs.redraw()
```

makes VFP work entirely as expected. Georg has enough information now to look into it. But it’s not a high priority, so we can leave this just as a reminder here for later.

**Comment by schriftgestalt** [comment]
can you try this in the mouseDidMove_:
```
	def mouseDidMove_(self, notification):
		try:
			notification.object().window().windowController().activeEditViewController().graphicView().setNeedsDisplay_(True)
		except Exception as e:
			import traceback
			print(traceback.format_exc())
```
It will only redraw the edit view that the mouse is over. So it might avoid the tow fonts problem. (that we should fix, too).

**Comment by Mark2Mark** [comment]
🍀 This w❤️rks like a charm 🍀

**Comment by Mark2Mark** [comment]
Thank you too!
