### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by justanotherfoundry** [jenskutilek/RedArrow-Glyphs#38]
Thanks for the tool! Seems very handy.

After setting the Preferences, I get the following error:

Traceback (most recent call last):
  File "GlyphsApp/GlyphsApp/plugins.py", line 1158, in drawForegroundForLayer_options_
  File "plugin.py", line 172, in foreground
    self._updateOutlineCheck(layer)
  File "plugin.py", line 289, in _updateOutlineCheck
    self.outline_test.checkLayer()
  File "outlineTestGlyphs.py", line 356, in checkLayer
    self._runCurveTests(node)
  File "outlineTestGlyphs.py", line 386, in _runCurveTests
    self._checkInflectionsCurve(node)
  File "outlineTestGlyphs.py", line 568, in _checkInflectionsCurve
    ok, err = getInflectionsForCubic(
  File "outlineTestGlyphs.py", line 130, in getInflectionsForCubic
    if err_min < r < err_max:
TypeError: '<' not supported between instances of 'float' and 'objc.pyobjc_unicode'

Hope this helps!
– Tim

**Comment by jenskutilek** [comment]
You can reset the values via Macro Panel:

```python
Glyphs.defaults["de.kutilek.RedArrow.inflection_min"] = 0.3
Glyphs.defaults["de.kutilek.RedArrow.inflection_max"] = 0.7
```

**Comment by schriftgestalt** [comment]
You probably should add a `float()` around user defaults call. I just added `Glyphs.floatDefaults[]`to help with that.

**Comment by jenskutilek** [comment]
I added a `NSNumberFormatter` to the vanilla `EditText` field and then call `NSDecimalNumber.floatValue()` on the result.

**Comment by jenskutilek** [comment]
`float(...)` doesn't work on NSDecimalNumber unfortunately … so the solution required a bit of hacking.

**Comment by schriftgestalt** [comment]
O meant doing the `float()` why you get the values out of the defaults, not when you put them in.

**Comment by justanotherfoundry** [comment]
Thanks for the quick action!
