### ISSUE TITLE
Issue with RedArrow-Glyphs

### ISSUE THREAD

**Issue by MajusCorp** [jenskutilek/RedArrow-Glyphs#4]
This is supposed to be only for Glyphs2, but if one double-clicks on the Reporter file to do the install it activates the older Glyphs app when both versions are installed but neither is open. It probably won't be a problem as long as anyone installing it notices that Glyphs v1.x.x is open, not G2.

**Comment by jenskutilek** [comment]
The plugin install location is the same for Glyphs 1 and 2, that means double-clicking will work either way.

**Comment by CatharsisFonts** [comment]
I can't see the menu options. I'm using Glyphs build (789). There are none of the files mentioned in your Troubleshooting section lying around.

**Comment by jenskutilek** [comment]
Could you check if there are any Glyphs-/RedArrow-related messages in Console.app while launching Glyphs?

**Comment by CatharsisFonts** [comment]
Dear Jens, 
that is indeed the case:
![screen shot 2015-09-02 at 12 31 21](https://cloud.githubusercontent.com/assets/13754106/9628840/95c90a2c-516e-11e5-8f28-0b4893a009b5.jpg)

**Comment by jenskutilek** [comment]
Please try the new version: https://github.com/jenskutilek/RedArrow-Glyphs/releases/tag/v0.3.4

It should work now.

**Comment by CatharsisFonts** [comment]
Sorry, it doesn't...
![screen shot 2015-09-02 at 15 56 50](https://cloud.githubusercontent.com/assets/13754106/9633108/51014ffe-518b-11e5-9623-a303b895e064.jpg)

**Comment by CatharsisFonts** [comment]
I thought it didn't work, but it does now — I just had to restart Glyphs. Thanks!  :smile:

**Comment by jenskutilek** [comment]
Great!
