### ISSUE TITLE
Feature request: Hovering on arrow should allow me to insert node

### ISSUE THREAD

**Issue by clauseggers** [jenskutilek/RedArrow-Glyphs#40]
Hi Jens, I have an idea for improvement. Often Glyphs is not smart enough to insert extrema nodes, but Red Arrows of course sees them. It would be handy to be able to click on the arrows (or a click + some command key) to insert a node at the extremum without having to zoom in and out and change tool to do it.

<img width="647" alt="Screenshot 2023-07-22 at 14 30 34" src="https://github.com/jenskutilek/RedArrow-Glyphs/assets/868987/126eb3d6-9847-4ceb-834b-9ecdabe024a0">

**Comment by schriftgestalt** [comment]
The "Add Extremes" command will not add nodes when it sill create a visible bump, like in this case. And you are totally fine without that extreme point in an italic font. If you really need to add it, use the pen tool, press the shift key and click anywhere on that segments. It will add the closest extreme node or inflection on that segment.

**Comment by clauseggers** [comment]
Alright, but since when do we not need to set extrema? Is it a reaction to changes in the Windows rendering engine?
PS: I didn’t know about the Shift+penclick, neat.

**Comment by schriftgestalt** [comment]
You probably don't need those extremes as long as you don't like to attach horizontal TrueType hints to them. But Jens might have more details about this.

**Comment by clauseggers** [comment]
Hmm – I was under the impression that in lieu of horizontal hints the Windows rendering engine would use the extrema.

**Comment by schriftgestalt** [comment]
No. It will just render the shape as is and the subpixel rendering is dealing with the rest.

**Comment by clauseggers** [comment]
Okay, noted.

**Comment by jenskutilek** [comment]
@schriftgestalt is right, those extrema on the right side are the least important to set, unless you want to hint the stem there. They are not used for any calculations in the font, e.g. the sidebearings.

The extrema on a similar (round) left side of a glyph matter more, because the left sidebearing is actually stored in the font, so missing extrema there may lead to small rounding errors.
