### ISSUE TITLE
Some incorrect smooth connections not flagged

### ISSUE THREAD

**Issue by hbeier** [jenskutilek/RedArrow-Glyphs#6]
I believe the image below explains it all. 

<img width="586" alt="screen shot 2016-03-06 at 11 59 23" src="https://cloud.githubusercontent.com/assets/10968309/13554937/2a78cfd4-e393-11e5-9571-dabe76855551.png">

**Comment by jenskutilek** [comment]
The smooth connection test checks whether the shorter handle of each pair is in the best possible position. If the outline detail we are looking at is very small, the font grid (usually 1000 units per em together with a Grid Spacing of 1 in the font info box) may prevent that the handle is placed at an actually smooth position. To fix this you would have to increase the upm value or disable the grid by setting it to 0. 

But beware when the grid is turned off, the RedArrow tests don’t work anymore, because they are only able to check integer coordinates.

**Comment by hbeier** [comment]
I understand your logic, but I think it doesn’t apply to my example. Most incorrect smooth connections are flagged correctly, only _some_ don’t. If I understand it correctly, the plugin uses some sort of angle threshold to determine if the connection should be flagged or not. This may be wrong, but it is how I imagine it works. For example, if the angle between handles is not 180° but it is between 179° and 181°, the plugin flags it as possibly incorrect smooth connection. Currently it ignores if the node is blue (corner) or green (smooth).

My suggestion is to implement an additional type of verification. If the node is green (smooth) and the angle between its handles is not 180°, it should be flagged. The reason is that the example above was interpolated between two masters. I probably should have been more careful when designing the masters to avoid these types of kinks, but I think Show Red Arrows could spot these errors too.

Here is another example. The first path shows the plugin is working. The second one should not be flagged, so it is correct again. However, the third path has a mistake (green node but not smooth handles) that the plugin could catch.
<img width="372" alt="screen shot 2016-03-10 at 16 34 09" src="https://cloud.githubusercontent.com/assets/10968309/13686843/9c4f1fe4-e6f6-11e5-9c20-cc2148a57107.png">

**Comment by jenskutilek** [comment]
I see. The type of node (blue/green) is not taken into consideration at the moment. So the algorithm doesn't flag connections that noticeable not smooth, because they could be intentional corners in the outline. I will try if it is possible to use the node connection type to improve the results.

**Comment by jenskutilek** [comment]
I think I have improved the detection in 96c4579. Please try if you like.

**Comment by hbeier** [comment]
It is not working for me. In fact, all flags stopped working. I’ve tested in the latest stable version of Glyphs (827) and latest beta (856).

<img width="580" alt="screen shot 2016-03-11 at 22 08 58" src="https://cloud.githubusercontent.com/assets/10968309/13719567/5883cf36-e7d6-11e5-9419-dfdb2244beb5.png">

**Comment by jenskutilek** [comment]
Please try again with the latest version, I fixed a bug ...

**Comment by jenskutilek** [comment]
Oh, and you need the latest `GSPen.py` and `objectsGS.py` from https://github.com/schriftgestalt/Glyphs-Scripts/tree/develope installed.

**Comment by hbeier** [comment]
Great, it works again!

<img width="358" alt="screen shot 2016-03-12 at 11 41 57" src="https://cloud.githubusercontent.com/assets/10968309/13723547/8ac850f4-e847-11e5-9035-936182093d9c.png">

However, I had GSPen.py and objectGS.py on a subfolder (I like cloning repos with GitHub Desktop app). After I moved them to the Scripts folder root, it worked.

Thanks for your help!

**Comment by jenskutilek** [comment]
You're welcome!

If you want to keep the script folder up to date with a cloned GitHub repository, you can put a soft link to the repo files `GSPen.py` and `objectsGS.py` into the Glyphs scripts folder, in Terminal like so:

```
$ ln -s "~/Path/to/repo/Glyphs-Scripts/GSPen.py" "~/Library/Application Support/Glyphs/Scripts/"
$ ln -s "~/Path/to/repo/Glyphs-Scripts/objectsGS.py" "~/Library/Application Support/Glyphs/Scripts/"
```

(This works at least in the current beta versions)
