### ISSUE TITLE
RA 0.44 no text appearing close to the arrows

### ISSUE THREAD

**Issue by synthview** [jenskutilek/RedArrow-Glyphs#7]
Hello, no text appears close to the arrows. I’m on G2 Version 2.3b (862), Mavericks OS.

**Comment by jenskutilek** [comment]
I have hidden the text labels by default now. You can get them back via the context menu – Show Error Labels.

Maybe I should save this setting, so you don’t have to switch them back on every time Glyphs restarts.

**Comment by synthview** [comment]
Ok thanks! Yes saving setting would be great :)
