### ISSUE TITLE
Visualisation problem  

### ISSUE THREAD

**Issue by SabinaKipara** [jenskutilek/RedArrow-Glyphs#8]
Hello! I have been using Red Arrow for a while, and it worked very well, but when I installed the new version, I don't see the plugin in Glyphs View window. It appears on my addons list though. 

Any suggestions?
Thank you!

**Comment by jenskutilek** [comment]
Which version of Glyphs are you using?

**Comment by SabinaKipara** [comment]
2.2.2 (827)

**Comment by jenskutilek** [comment]
Ah, ok, for Glyphs 2.2 you should use the older release: https://github.com/jenskutilek/RedArrow-Glyphs/releases/tag/v0.3.7

The newest version of Red Arrow will only work in the Glyphs 2.3 beta versions.

**Comment by SabinaKipara** [comment]
Great! It works now! Thank you so much

**Comment by jenskutilek** [comment]
The latest update (v0.4.7) adds backwards compatibility so the same version of the plugin can be used in Glyphs 2.2 and 2.3.
