### ISSUE TITLE
Suppress fractional coordinates when Glyphs grid is subdivided

### ISSUE THREAD

**Issue by NicholasSloan** [jenskutilek/RedArrow-Glyphs#9]
Hi, using RedArrow-Glyphs in a file where the unit grid-spacing has a subdivision of 5, almost every BCP is arrowed as an error with Fractional Coordinates, though in this context that is not an error. Could RedHandles be tweaked to respect the Glyphs grid settings?
Thanks

**Comment by jenskutilek** [comment]
Thanks for reporting. This should now work in the latest version. Could you try it?

**Comment by NicholasSloan** [comment]
Hi Jens,

With Glyphs 2.3.2 (911) and redArrow 0.52 (on Mac 10.10.5) I am still finding paths littered with Fractional Corordinate arrows, even though the grid settings are 1/5. Do you want a screenshot?

Naturally I relaunched Glyphs, and I also tried a restart in case there might be any caching issue.

Thanks,
Nick

**Comment by jenskutilek** [comment]
Could you send me your Glyphs file to webmail@kutilek.de?

**Comment by jenskutilek** [comment]
OK, I found it and fixed it. Comparison of floating point numbers is tricky ;)

**Comment by NicholasSloan** [comment]
> OK, I found it and fixed it. Comparison of floating point numbers is tricky ;)

I imagine so. Congratulations!
Many thanks,
Nick
